---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: appsec
  name: appsec-trusselmodellering-slackbot
  namespace: appsec
spec:
  image: {{ image }}
  port: 3000
  replicas:
    min: 1
    max: 1
  liveness:
    path: /internal/is_alive
  readiness:
    path: /internal/is_alive
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 128Mi
  accessPolicy:
    outbound:
      external:
        - host: slack.com
        - host: api.slack.com
        - host: wss-primary.slack.com
        - host: api.trello.com
        - host: trello.com
  env:
    - name: PORT
      value: "3000"
  envFrom:
    - secret: appsec-trusselmodellering-bot-secrets